# Generated by Django 5.1.7 on 2025-03-07 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IceCream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('static_image_path', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IceCreamBall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ice_cream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icecreams.icecream')),
            ],
        ),
        migrations.CreateModel(
            name='IceCreamBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=40)),
                ('ice_cream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icecreams.icecream')),
            ],
        ),
    ]
