# Generated by Django 5.1.7 on 2025-03-07 21:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icecreams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='icecreamball',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
