# Generated by Django 5.1.7 on 2025-03-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icecreams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icecream',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
