# Generated by Django 5.1.7 on 2025-03-10 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icecreams', '0002_icecreamball_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='icecreambucket',
            name='initial_quantity',
            field=models.IntegerField(default=40),
        ),
    ]
