# Generated by Django 5.1.7 on 2025-03-10 06:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icecreams', '0003_icecreambucket_initial_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icecreambucket',
            name='initial_quantity',
            field=models.IntegerField(default=40, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ice_cream_balls', models.ManyToManyField(to='icecreams.icecreamball')),
            ],
        ),
    ]
