# Generated by Django 5.1.7 on 2025-03-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icecreams', '0004_alter_icecreambucket_initial_quantity_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='name',
            field=models.CharField(default='', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
